=== brianjimenez/benchmarking-data-model/json-schemas/community_extended.json
{
	"id": "https://www.elixir-europe.org/excelerate/WP2/json-schemas#Community",
	"$schema": "http://json-schema.org/draft-04/hyper-schema#",
	"title": "Community concept (ELIXIR-EXCELERATE WP2 Benchmarking schemas)",
	"type": "object",
	"properties": {
		"_id": {
			"title": "The unique id of the community. It should be something unique of the community (for instance, an acronym)",
			"type": "string",
			"minLength": 1
		},
		"_schema": {
			"title": "The document schema",
			"type": "string"
		},
		"name": {
			"title": "Short community name",
			"minLength": 1,
			"type": "string"
		},
		"acronym": {
			"title": "Unique community acronym",
			"minLength": 1,
			"type": "string"
		},
		"status_id": {
			"title": "_id(s) of the current community status(es)",
			"type": "array",
			"minLength": 1,
			"items": {
				"type": "string",
				"minLength": 1
			}
		},
		"description": {
			"title": "Long community name or description",
			"type": "string"
		},
		"links": {
			"title": "Optional links related to the community",
			"type": "array",
			"minLength": 1,
			"items": {
				"type": "object",
				"properties": {
					"uri": {
						"title": "The URI of the link related to the community",
						"type": "string",
						"format": "uri"
					},
					"label": {
						"title": "The type of URI",
						"type": "string",
						"enum": ["PublicationDOI","LinkedInGroup","MainSite","DataSite"]
					}
				},
				"additionalProperties": false,
				"required": [
					"uri",
					"label"
				]
			}
		},
		"community_contacts": {
			"title": "_id of the contacts of the responsible researchers in charge of the community coordination",
			"type": "array",
			"minLength": 1,
			"items": {
				"type": {"$ref": "contact.json"},
				"minLength": 1
			}
		},
                "Contact": {
                    "Title": "Contacts list",
                    "type": "array",
                    "items": {
                        "type": {"$ref":"contact.json"}
                    }
                },
                "BenchmarkingEvent" : {
                    "Title": "BenchmarkingEvents list",
                    "type": "array",
                    "items": {
                        "type": {"$ref":"benchmarkingEvent.json"}
                    }
                },
                "Metrics": {
                    "Title": "Metrics list",
                    "type": "array",
                    "items": {
                        "type": {"$ref": "metrics.json"}
                    }
                },
                "TestEvent": {
                    "Title": "TestEvent list",
                    "type": "array",
                    "items": {
                        "type": {"$ref": "testEvent.json"}
                    }           
                },
                "Dataset": {
                    "Title": "Datasets list",
                    "type": "array",
                    "items": {
                        "type": {"$ref":"dataset.json"}
                    }
                },
                "Tool" : {
                    "Title": "Tools list",
                    "type": "array",
                    "items": {
                        "type": {"$ref":"tool.json"}
                    }
                }
	},
	"additionalProperties": true,
	"required": ["_id","_schema","name","acronym","status_id","community_contacts"],
	"dependencies": {}
}

=== brianjimenez/benchmarking-data-model/prototype-data/cameo_prototype_data_fixed/cameo_community_Structure.json
{
	"_id": "Structure Prediction",
	"_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/0.3/Community",
	"name": "Structure prediction community",
	"acronym": "strpred",
	"status_id": [
		"TBD"
	],
	"description": "Whatever",
	"links":[
		{
			"label":"MainSite",
			"uri":"https://en.wikipedia.org/wiki/CASP"
		},
		{
			"label":"PublicationDOI",
			"uri":"http://dx.doi.org/10.1093/database/bat031"
		}
	],
	"community_contacts":
		[
				"Juergen.Haas",
				"Torsten.Schwede"
		]
	
	
}
